twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        cartController: "@App\\Controller\\CartController"
        ImagePathGenerator: "@App\\Service\\Image\\ImagePathGenerator"
    path:
        - "vendor/knplabs/knp-paginator-bundle/templates/Pagination"